namespace SourceGenerator.HealthChecks;

using NetEvolve.CodeBuilder;

internal static class CodeGenerator
{
    public static CSharpCodeBuilder ConfigurableHealthCheck(
        ICandidate candidate,
        Action<CSharpCodeBuilder>? additionalCode = null,
        bool withWin32ExceptionHandling = false
    )
    {
        var cb = new CSharpCodeBuilder(500)
            .AppendLine("// <auto-generated />")
            .Append("namespace ")
            .Append(candidate.Namespace)
            .AppendLine(';')
            .AppendLine()
            .AppendLine("using System;")
            .AppendLine("using System.ComponentModel;")
            .AppendLine("using System.Diagnostics;")
            .AppendLine("using System.Runtime.CompilerServices;")
            .AppendLine("using System.Threading;")
            .AppendLine("using System.Threading.Tasks;")
            .AppendLine("using Microsoft.Extensions.Diagnostics.HealthChecks;")
            .AppendLine("using Microsoft.Extensions.Options;")
            .AppendLine("using NetEvolve.Extensions.Tasks;")
            .AppendLine();

        _ = cb.AppendLine(
                $"partial class {candidate.Name}(IOptionsMonitor<{candidate.OptionsTypeName}> optionsMonitor)"
            )
            .Intend()
            .AppendLine(": IHealthCheck");

        using (cb.Scope())
        {
            _ = cb.AppendLine(
                    $"private readonly IOptionsMonitor<{candidate.OptionsTypeName}> _optionsMonitor = optionsMonitor;"
                )
                .AppendLine(
                    $"private readonly {candidate.OptionsTypeName} _defaultConfiguration = new {candidate.OptionsTypeName}();"
                )
                .AppendLine()
                .AppendXmlDocInheritDoc();

            using (
                cb.ScopeLine(
                    "public async Task<HealthCheckResult> CheckHealthAsync(HealthCheckContext context, CancellationToken cancellationToken = default)"
                )
            )
            {
                _ = cb.AppendLine("ArgumentNullException.ThrowIfNull(context);")
                    .AppendLine()
                    .AppendLine("var name = context.Registration.Name;")
                    .AppendLine("var failureStatus = context.Registration.FailureStatus;")
                    .AppendLine();

                using (cb.ScopeLine("if (cancellationToken.IsCancellationRequested)"))
                {
                    _ = cb.HealthCheckUnhealthy("Cancellation requested.");
                }

                _ = cb.AppendLine();

                using (cb.ScopeLine("try"))
                {
                    _ = cb.AppendLine("var options = _optionsMonitor.Get(name);");

                    using (cb.ScopeLine($"if (options?.Equals(_defaultConfiguration) != false)"))
                    {
                        _ = cb.HealthCheckUnhealthy("Missing configuration.");
                    }

                    _ = cb.AppendLine()
                        .AppendLine(
                            "return await ExecuteHealthCheckAsync(name, failureStatus, options, cancellationToken).ConfigureAwait(false);"
                        );
                }
                if (withWin32ExceptionHandling)
                {
                    using (cb.ScopeLine("catch (Exception wex) when (wex.InnerException is Win32Exception)"))
                    {
                        _ = cb.HealthCheckUnhealthy("Unexpected Win32 exception");
                    }
                }
                using (cb.ScopeLine("catch (Exception ex)"))
                {
                    _ = cb.HealthCheckUnhealthy("Unexpected error.", "ex");
                }
            }

            _ = cb.AppendLine();

            if (additionalCode is not null)
            {
                additionalCode(cb);
            }
        }

        return cb;
    }
}
