name: CI - SqlServer

on:
  push:
    branches: [ main ]
    paths:
      - src/HealthChecks.Abstractions.Shared/**/*
      - src/HealthChecks.SqlServer.Legacy/**/*
  pull_request:
    branches: [ main ]
    paths:
      - src/HealthChecks.Abstractions.Shared/**/*
      - src/HealthChecks.SqlServer.Legacy/**/*

jobs:
  all:
    name: Build & Tests
    uses: dailydevops/pipelines/.github/workflows/cicd-dotnet.yml@main
    with:
      enableSonarQube: true
      dotnet-logging: ${{ inputs.dotnet-logging }}
      dotnet-version: |
        6.x
        7.x
        8.x
      dotnet-quality: preview
      dotnet-testfilter: "'UnitTest','IntegrationTest'"
      solution: ./src/HealthChecks.SqlServer.Legacy/HealthChecks.SqlServer.Legacy.slnf
    secrets: inherit
