name: Run Stryker.NET with Dashboard Reporting

on:
  schedule:
    # Change the cron expression to your desired schedule. This example runs every Monday and Thursday at 2 AM.
    - cron: '0 2 * * MON,THU'
      timezone: 'Europe/Berlin'

  workflow_dispatch:
    inputs:
      configurationFile:
        description: 'Path to the Stryker configuration file'
        required: false
        default: 'stryker-config.json'

jobs:
  all:
    if: github.run_id != 1
    name: Run Stryker.NET Mutation Testing
    uses: dailydevops/pipelines/.github/workflows/mutation-dotnet.yml@1654472d2498bd41e01367b68ecf2d01acdc92d8 # 2.4.11
    with:
      configurationFile: ${{ inputs.configurationFile || 'stryker-config.json' }}
    secrets: inherit

